name: e2e
on: 
  push:
    branches:
      - master
jobs:
  build:
    name: e2e
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v3

      - name: Install devcontainers
        uses: devcontainers/cli-action@v0.3
        with:
          runCmd: echo hi
        

